version: '3.7'

services:
  frontend:
    build:
      context: ./frontend
      target: dev
    ports:
      - "3000:3000"
    command: sh -c 'yarn start'
    volumes:
      - ./frontend:/code
      - ./frontend/node_modules:/code/node_modules
